spring:
  cloud:
    gateway:
      routes:
      - id: catalogo
        uri: http://127.0.0.1:8081
        predicates:
        - Path=/api/produtos**,/api/produtos/**
#        - GoldenCustomer=true
#        filters:
#        - StripPrefix=1
#        - AddRequestHeader=GoldenCustomer,true
#      - id: common_route
#        uri: http://127.0.0.1:8082
#        predicates:
#        - Path=/api/**
#        - name: GoldenCustomer
#          args:
#            golden: false
#            customerIdCookie: customerId
#        filters:
#        - StripPrefix=1
#        - AddRequestHeader=GoldenCustomer,false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
